[[mgr.prepend_keymap]]
on = "<C-n>"
run = '''
	shell 'dragon-drop -x -i -T "$1"' --confirm
'''

[[mgr.prepend_keymap]]
on = "y"
run = [
  '''
	shell 'for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list' --confirm
''',
  "yank",
]

# Use the augmented arrow up command for the k key
[[mgr.prepend_keymap]]
on = "k"
run = "plugin augment-command -- arrow -1"
desc = "Move cursor up"

# Use the augmented arrow down command for the j key
[[mgr.prepend_keymap]]
on = "j"
run = "plugin augment-command -- arrow 1"
desc = "Move cursor down"

# Use K to move up in the parent directory
[[mgr.prepend_keymap]]
on = "K"
run = "plugin augment-command -- parent_arrow -1"
desc = "Move cursor up in the parent directory"

# Use J to move down in the parent directory
[[mgr.prepend_keymap]]
on = "J"
run = "plugin augment-command -- parent_arrow 1"
desc = "Move cursor down in the parent directory"

# Use Ctrl + k to seek 5 units up in the preview pane
[[mgr.prepend_keymap]]
on = "<C-k>"
run = "seek -5"
desc = "Seek up 5 units in the preview pane"

# Use Ctrl + j to seek 5 units down in the preview pane
[[mgr.prepend_keymap]]
on = "<C-j>"
run = "seek 5"
desc = "Seek down 5 units in the preview pane"

# Use the augmented enter command for the l key
[[mgr.prepend_keymap]]
on = "l"
run = "plugin augment-command -- enter"
desc = "Enter the child directory, or open the file"

# Use the augmented enter command for the <Enter> key
[[mgr.prepend_keymap]]
on = "<Enter>"
run = "plugin augment-command -- enter"
desc = "Enter the child directory, or open the file"

# Use the augmented enter command for the <S-Enter> key
[[mgr.prepend_keymap]]
on = "<S-Enter>"
run = "plugin augment-command -- enter --interactive"
desc = "Enter the child directory, or open the file interactively"

# Use the augmented enter command for the <Right> key
# but without skipping directories
[[mgr.prepend_keymap]]
on = "<Right>"
run = "plugin augment-command -- enter --no-skip"
desc = "Enter the child directory, or open the file"

# Use the augmented leave command for the h key
[[mgr.prepend_keymap]]
on = ["h"]
run = "plugin augment-command -- leave"
desc = "Go back to the parent directory"

# Use the augmented leave command for the <Left> key
# but without skipping directories
[[mgr.prepend_keymap]]
on = ["<Left>"]
run = "plugin augment-command -- leave --no-skip"
desc = "Go back to the parent directory"

# Use the augmented tab create command for the t key
[[mgr.prepend_keymap]]
on = "t"
run = "plugin augment-command -- tab_create --current"
desc = "Create a new tab with CWD"

# Use the augmented open to open files interactively with O
[[mgr.prepend_keymap]]
on = "O"
run = "plugin augment-command -- open --interactive"
desc = "Open selected files interactively"

# Use u to unselect and unyank all files
[[mgr.prepend_keymap]]
on = "u"
run = ["toggle_all --state=off", "unyank"]
desc = "Unselect all files and also unyank cut files"

# Use _ to create a new file or directory
[[mgr.prepend_keymap]]
on = "_"
run = "plugin augment-command -- create"
desc = "Create a file or directory"

# Use + to create a new file or directory
[[mgr.prepend_keymap]]
on = "+"
run = "plugin augment-command -- create"
desc = "Create a file or directory"


[[mgr.prepend_keymap]]
on = "p"
run = "plugin augment-command -- paste"
desc = "Paste the files"

[[mgr.prepend_keymap]]
on = "P"
run = "plugin augment-command -- paste --force"
desc = "Paste the files (overwrite if the destination exists)"

# Use r to rename files with the cursor before the file extension
[[mgr.prepend_keymap]]
on = "r"
run = "plugin augment-command -- rename --cursor=before_ext"
desc = "Rename a file or directory"

[[mgr.prepend_keymap]]
on = "R"
run = "plugin augment-command -- rename --empty=all"
desc = "Rename file and remove the whole file name"

[[mgr.prepend_keymap]]
on = ["e", "c"]
run = "cd ~/.config/yazi"
desc = "Edit the Yazi configuration"

# Use gc to go to the config directory
[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/.config"
desc = "Go to the config directory"

# Use gb to go to the books folder 
[[mgr.prepend_keymap]]
on = ["g", "b"]
run = "cd ~/Books"
desc = "Go to the books folder"

# Use gm to go to the documents folder
[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd ~/Documents"
desc = "Go to the documents folder"

# Use  gp to to to phd folders
[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/Documents/phd_thesis"
desc = "Go to phd folder"

# The mapping to open the mount plugin
[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"
desc = "Open the mount manager"

[[mgr.prepend_keymap]]
on = ["c", "a"]
run = "plugin compress"
desc = "Archive selected files"
