[manager]
sort_dir_first = true
image_quality = 50

[opener]
edit = [{ run = 'nvim "$@"', block = true }]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', desc = "Open", orphan = true }]
# ...
[plugin]
prepend_previewers = [{ mime = "text/csv", run = "miller" }]
