[mgr]
sort_dir_first = true
image_quality = 50

[opener]
edit = [{ run = 'nvim "$@"', block = true }]
play = [{ run = 'mpv "$@"', orphan = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', desc = "Open", orphan = true }]
extract = [
  { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
  { run = 'ya pub extract --list %*', desc = "Extract here", for = "windows" },
]
# ...
