[pyprland]
plugins = [
  # "expose",
  # "fetch_client_menu",
  # "lost_windows",
  # "magnify",
  "scratchpads",
  # "shift_monitors",
  "toggle_special",
  # "workspaces_follow_focus",
  "shortcuts_menu",
]

[pyprland.variables]
term_classed = "kitty -1 --instance-group kitty_sock -o allow_remote_control=yes --listen-on unix:/tmp/kitty_sock --class"
kw = "-o initial_window_width"
kh = "-o initial_window_height"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] term [kw]=65c [kh]=11c"
match_by = "class"
class = "term"
# size = "504px 225px"
position = "33% 4%"
# margin = "%"
max_size = "1920px 100%"
process_tracking = false


[scratchpads.btop]
animation = "fromleft"
command = "[term_classed] btop [kw]=65c [kh]=20c -e btop"
match_by = "class"
class = "btop"
# size = "427px 396px"
position = "1% 55%"
offset = "10px"
process_tracking = false
skip_windowrules = ["workspace", "float"]
# allow_special_workspaces = true


[scratchpads.nchat]
animation = "fromLeft"
command = "[term_classed] nchat [kw]=65c [kh]=15c -e nchat"
match_by = "class"
class = "nchat"
# size = "504px 270px"
offset = "10px"
position = "1% 23%"
process_tracking = false
lazy = false

[scratchpads.ncmpcpp]
animation = "fromBottom"
command = "[term_classed] ncmpcpp [kw]=65c [kh]=14c -e ncmpcpp"
match_by = "class"
position = "58% 60%"
class = "ncmpcpp"
process_tracking = false


[scratchpads.yazi]
animation = "fromRight"
command = "[term_classed] yazi [kw]=70c [kh]=14c -e yazi ~/"
match_by = "class"
class = "yazi"
position = "55% 23%"
offset = "60px"
max_size = "1920px 100%"
process_tracking = false


[scratchpads.obsiterm]
animation = "fromLeft"
command = "[term_classed] obsiterm [kw]=70c [kh]=30c -d /home/samtrek/Documents/'Obsidian Vault' -e nvim"
match_by = "class"
class = "obsiterm"
position = "1% 37%"
offset = "60px"
process_tracking = false

[scratchpads.Thunar]
animation = "fromRight"
command = "Thunar"
match_by = "class"
class = "Thunar"
size = "504px 270px"
max_size = "1920px 100%"
lazy = true
pinned = false
# process_tracking = false

[scratchpads.alpaca]
animation = "fromRight"
command = "alpaca"
match_by = "class"
class = "com.jeffser.Alpaca"
size = "402px 761px"
offset = "60px"
lazy = true
# process_tracking = false

[scratchpads.rcode]
animation = "fromBottom"
command = "[term_classed] rcode -d /home/samtrek/Documents/phd_thesis/ -e nvim"
match_by = "class"
class = "rcode"
process_tracking = false

[shortcuts_menu.entries]

Relayout = "pypr relayout"
"waybar reload" = "killall -SIGUSR2 waybar"
"Hyprland socket" = 'kitty  socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"'
"Hyprland logs" = 'kitty tail -f $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log'


"Color picker" = [
  { name = "format", options = [
    "hex",
    "rgb",
    "hsv",
    "hsl",
    "cmyk",
  ] },
  "sleep 0.2; hyprpicker --format [format] | wl-copy", # sleep to let the menu close before the picker opens
]

screenshot = [
  { name = "what", options = [
    "output",
    "window",
    "region",
    "active",
  ] },
  "hyprshot -m [what] -o /tmp -f shot_[what].png",
]

pypr = [
  { name = "pypr_type", options = [
    "reload",
    "edit",
    "toggle",
  ] },
  "pypr [pypr_type]",
]

annotate = [
  { name = "fname", command = "ls /tmp/shot_*.png" },
  "satty --filename '[fname]' --output-filename '/tmp/annotated.png'",
]
