[pyprland]
plugins = [
  "expose",
  "fetch_client_menu",
  "lost_windows",
  "magnify",
  "scratchpads",
  "shift_monitors",
  "toggle_special",
  "workspaces_follow_focus",
]

[pyprland.variables]
term_classed = "kitty -1 --instance-group kitty_sock -o allow_remote_control=yes --listen-on unix:/tmp/kitty_sock --class"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] term"
match_by = "class"
class = "term"
size = "35% 25%"
max_size = "1920px 100%"
process_tracking = false


[scratchpads.btop]
animation = "fromTop"
command = "[term_classed] btop -e btop"
match_by = "class"
class = "btop"
size = "45% 45%"
max_size = "1920px 100%"
process_tracking = false


[scratchpads.nchat]
animation = "fromTop"
command = "[term_classed] nchat -e nchat"
match_by = "class"
class = "nchat"
size = "35% 30%"
max_size = "1920px 100%"
process_tracking = false

[scratchpads.ncmpcpp]
animation = "fromTop"
command = "[term_classed] ncmpcpp -e ncmpcpp"
match_by = "class"
class = "ncmpcpp"
size = "35% 30%"
max_size = "1920px 100%"
process_tracking = false
