version = "1.1.15"

[class]
VirtualBox = ""
Postman = ""
nchat = ""
Slack = ""
foot = ""
balena-etcher = ""
Steam = ""
firefoxdeveloperedition = ""
pavucontrol = ""
Element = ""
vlc = ""
Code = ""
WebCord = ""
Zotero = ""
"[Ff]irefox" = ""
Chromium = ""
Thunderbird = ""
Nightly = ""
thunderbird = ""
"(?i)Kitty" = ""
"term" = ""
evince = ""
transmission-remote-gtk = ""
Emacs = ""
"VirtualBox Manager" = ""
"/yarn/" = ""
"Chia Blockchain" = ""
libreoffice-writer = ""
Signal = ""
"org.gnome.Calculator" = ""
"GitHub Desktop" = ""
DEFAULT = " -"
remarkhub = ""
discord = ""
Gimp = ""
firefox = ""
"/nvim ?\\w*/" = ""
"/(?i)^Github.*Firefox/" = ""
thunar = ""
code-oss = ""
"/node/" = ""
"org.freecadweb.FreeCAD" = ""
"(?i)waydroid.*" = "droid"
eog = ""
"VirtualBox Machine" = ""
"com/.https://ultimaker.UltiMaker-Cura" = ""
yazi = ""
Bitwarden = ""
Spotify = ""
Google-chrome = ""
Insomnia = ""
"/npm/" = ""
"org.gnome.Nautilus" = ""
ncmpcpp = ""
jetbrains-studio = ""
google-chrome = ""
"org.qbittorrent.qBittorrent" = ""
libreoffice-calc = ""
Alacritty = ""

[class_active]
"(?i)ExampleOneTerm" = "<span foreground='red'>{icon}</span>"
DEFAULT = ""

[initial_class]

[initial_class_active]

[workspaces_name]
1 = "one"
7 = "seven"
9 = "nine"
0 = "zero"
2 = "two"
4 = "four"
8 = "eight"
10 = "ten"
3 = "three"
5 = "five"
6 = "six"

[title_in_class."(?i)kitty"]
"(?i)neomutt" = "neomutt"

[title_in_class_active."(?i)firefox"]
"(?i)twitch" = "<span color='purple'>{icon}</span>"

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
"" = "^$"
aProgram = "^$"
"[Ss]team" = "^(Friends List.*)?$"
"(?i)TestApp" = ""

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = " "
workspace = "{id}:{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "{icon}"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
