#! /bin/sh
gsettings set org.gnome.desktop.interface gtk-theme Graphite-teal-compact-nord &

pkill swaybg
swaybg -o DVI-I-1 -i /home/samtrek/Documents/walpapers/luffy5.jpg -m fill -o DVI-I-2 -i /home/samtrek/Documents/walpapers/demon3.jpg -m fill -o eDP-1 -i /home/samtrek/Documents/walpapers/demon2.jpg -i '/home/samtrek/Documents/walpapers/demon3.jpg' &
